### ISSUE TITLE
OS X 安装失败

### ISSUE THREAD

**Issue by faceair** [qiu8310/smart-npm#1]
![qq20150409-1](https://cloud.githubusercontent.com/assets/3659110/7049543/fef4b720-de4c-11e4-83fe-a9fd43eb9ad9.png)

**Comment by qiu8310** [comment]
非常感谢反馈！

安装之前会帮你备份原来的 `npm` 命令文件，你可能没有对原 `npm` 文件的写权限，所以在备份文件的时候出错了，你可以用命令 `ls -l $(which npm)` 确认下你是否有写权限。

如果确实是没有写权限，你可以安装时用管理员权限安装，即 `sudo  npm install --global --registry=https://registry.npm.taobao.org/`

我在下一个版本改善下安装过程的体验，再一次感谢您的反馈！

**Comment by faceair** [comment]
![qq20150409-1 2x](https://cloud.githubusercontent.com/assets/3659110/7060971/33fbe6a8-debd-11e4-87e9-ca28f61a296c.png)
![qq20150409-2 2x](https://cloud.githubusercontent.com/assets/3659110/7060972/3690b74a-debd-11e4-8ff3-6a6ce53978c7.png)

![qq20150409-3 2x](https://cloud.githubusercontent.com/assets/3659110/7060980/6c5e180e-debd-11e4-8b1d-110441a35fbc.png)

[npm-debug.log](http://qiniu-up.qiniudn.com/3b4ad460d97bcc23b4a82cefc08d4892)

看起来这里并不是权限问题，而好像跟我的shell有关，好像是因为fish不支持&&

**Comment by qiu8310** [comment]
你这次错误提示和上次不一样了，看来确实不是权限问题。

我晚上找时间看下！

**Comment by qiu8310** [comment]
实在想不到有什么很好的方法，现在把自动备份 npm 功能去掉了，现在需要你在安装的时候手动替换原来的 npm，比如可以使用下面的命令：

```
# Mac 或者 Linux 用户
ln -s $(npm root -g)/npm/bin/npm-cli.js $(dirname $which npm))/npm-original  # 将系统的 npm 备份到 npm-original
npm install --global smart-npm --registry=https://registry.npm.taobao.org/
```
