### ISSUE TITLE
window8安装了smart-npm之后，输入npm错误

### ISSUE THREAD

**Issue by chaegumi** [qiu8310/smart-npm#11]
'npm'不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by chaegumi** [comment]
把我的npm命令给弄没了，其它的命令正常

**Comment by qiu8310** [comment]
是的，安装 smart-npm 后会替换原来的 npm，这说明你没安装成功，但你反馈的信息太少了，我无法确定你问题出在什么地方。

如果你想快速恢复你原来的 npm，你重新安装下 node 就好了。

如果你确实想使用 smart-npm，可以回答下这几个问题，我帮你定位原因：

1. 你安装的是哪个版本的 smart-npm, 1.x.x 还是 2.x.x
2. 安装过程中有没有报什么错误，把错误信息反馈下（估计也找不到了）

另外，说下原理，这样你自己也可以方便的恢复 npm：
安装 npm 后会在安装的文件下生成一个 npm.cmd 文件，而你安装 smart-npm 时，会先将你的 npm.cmd 重命名成 _npm-original.cmd 文件，然后生成一个新的 npm.cmd。

出现你说的那个问题是新的 npm.cmd 没有生成，但旧的 npm.cmd 被替换成了 _npm-original.cmd 文件，所以你只要找到 npm.cmd 的安装目录，将里面的 _npm-original.cmd 替换成 npm.cmd 即可

**Comment by chaegumi** [comment]
我使用`npm install --global smart-npm --registry=https://registry.npm.taobao.org/` 这条命令安装的，安装过程中是有出错（大致是说找不到命令），估计也是安装过程中npm给弄没了，所以后续的一些东西就报npm错误了。没有你说的_npm-original.cmd这个文件。后边我是手动下载npm包，然后替换到环境变量目录中，就可以用了。

**Comment by qiu8310** [comment]
那算了，其实我自己以前安装也出现过问题，当时主要是目录权限问题。

那我还是发个新版本，不再替换原来的 npm，安装后自己手动替换吧
