### ISSUE TITLE
请问这个对 node.js 4.1.1 支持的怎么样

### ISSUE THREAD

**Issue by raiscui** [qiu8310/smart-npm#4]
以及  npm 3.x

**Comment by qiu8310** [comment]
smart-npm 和 node.js 无关，4.1.1 应该没问题。
至于 npm， smart-npm 自带了一个 npm，这个 npm 就是当前最新的稳定版本的 npm。

所以如果你安装了 smart-npm，那么你系统**自带的 npm 就会失效的**，项目首页有教你如何备份和恢复你系统自带的 npm 的方法。
