### ISSUE TITLE
windows下安装后出错

### ISSUE THREAD

**Issue by ziben** [qiu8310/smart-npm#5]
windows下，生成的快捷方式直接指向的是smart-npm.js，如果windows的js默认不是由node.exe执行的话，那么就会出现安装后npm不能用的问题。

**Comment by ziben** [comment]
我修改了js默认由node.exe执行，在cmd窗口下还是不能用啊。

**Comment by qiu8310** [comment]
不好意思，我刚发布 smart-npm@2.0.0，没有在 window 测试。发布 2.0 主要是因为 在 mac 上 smart-npm 无法通过 scripts 的方式覆盖原来的 npm，所以 2.0 是通过先删除原来的 npm，再添加一个用 smart-npm 生成的新 npm。

我刚在 window 上试了下，我这也没装成功，是说没有权限把原来的 npm 删除。不过装 smart-npm@1 是可以成功的，也许你也可以装1试试（功能上版本2和版本1没有太大的区别，主要是安装方式不一样），安装脚本：

```
npm install --global smart-npm@1 --registry=https://registry.npm.taobao.org/
```

如果还有问题麻烦将 npm 报错的信息也贴一下（发现通过覆盖原生的 npm 这种方法不是太稳定，不同的系统会有不同的问题）

**Comment by devilmengcry** [comment]
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.0.0/bin/node" "/root/.nvm/versions/node/v6.0.0/bin/npm" "install" "--global" "smart-npm" "--registry=https://registry.npm.taobao.org/"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE

npm ERR! smart-npm@2.0.0 postinstall: `node scripts/helper.js postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-npm@2.0.0 postinstall script 'node scripts/helper.js postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/helper.js postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1
