### ISSUE TITLE
cnpm registry  是不是可以去掉了？

### ISSUE THREAD

**Issue by gatspy** [qiu8310/smart-npm#57]
使用snpm以后是不是可以去掉.npmrc中的registry呢
`registry=https://registry.npm.taobao.org`

以下环境变量是不是也可以去掉了
``` shell
export NVM_NODEJS_ORG_MIRROR=https://npm.taobao.org/dist
export NVM_IOJS_ORG_MIRROR=https://npm.taobao.org/mirrors/iojs
```

奇怪的是，使用的淘宝的registry，npm search一用就报错，真不知道是为何。
正是由于这问题，才google到snpm。

**Comment by qiu8310** [comment]
是的，可以去掉， snpm 是在你运行的时候动态注入这些变量的。

如果是这些变量引起你的 npm 报错，那我觉得你用 snpm 可能也会一样（如上面说的，snpm 是在运行时注入这些变量）

**Comment by gatspy** [comment]
谢谢啊。npm 使用淘宝registry，search的时候出错，查看日志确实是淘宝的问题，不知道为什么淘宝镜像没有search接口。
