### ISSUE TITLE
centos6.5安装失败

### ISSUE THREAD

**Issue by devilmengcry** [qiu8310/smart-npm#6]
[root@iZ23oir9az1Z ~]# npm install --global smart-npm --registry=https://registry.npm.taobao.org/
npm WARN lifecycle smart-npm@2.0.0~preinstall: cannot run in wd %s %s (wd=%s) smart-npm@2.0.0 npm config set registry https://registry.npm.taobao.org/ /root/.nvm/versions/node/v6.0.0/lib/node_modules/.staging/smart-npm-ef71f992
/root/.nvm/versions/node/v6.0.0/bin/smart-npm -> /root/.nvm/versions/node/v6.0.0/lib/node_modules/smart-npm/bin/smart-npm.js

> smart-npm@2.0.0 postinstall /root/.nvm/versions/node/v6.0.0/lib/node_modules/smart-npm
> node scripts/helper.js postinstall

fs.js:1083
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: EACCES: permission denied, unlink '/root/.nvm/versions/node/v6.0.0/bin/npm'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:1083:18)
    at postInstall (/root/.nvm/versions/node/v6.0.0/lib/node_modules/smart-npm/scripts/helper.js:89:34)
    at Object.<anonymous> (/root/.nvm/versions/node/v6.0.0/lib/node_modules/smart-npm/scripts/helper.js:136:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Function.Module.runMain (module.js:575:10)
/root/.nvm/versions/node/v6.0.0/lib
└── (empty)

npm ERR! Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.0.0/bin/node" "/root/.nvm/versions/node/v6.0.0/bin/npm" "install" "--global" "smart-npm" "--registry=https://registry.npm.taobao.org/"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! smart-npm@2.0.0 postinstall: `node scripts/helper.js postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the smart-npm@2.0.0 postinstall script 'node scripts/helper.js postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the smart-npm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/helper.js postinstall
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs smart-npm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls smart-npm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
npm ERR! code 1

**Comment by qiu8310** [comment]
```
permission denied, unlink '/root/.nvm/versions/node/v6.0.0/bin/npm'
``

是没有权限删除原来的那个 npm 文件，smart-npm@2 会先将原来的 npm 删除，然后用 smart-npm 替换。 你可以安装 smart-npm@1 试试 `npm i -g smart-npm@1 --registry=https://registry.npm.taobao.org/`
 或者用 sudo 安装（但用 sudo 安装后可能每次都需要用 sudo 去执行 npm）

**Comment by qiu8310** [comment]
发了个新版本，在生成新的 npm 文件失败后会出一个提醒，方便你们根据自己的情况安装

![image](https://cloud.githubusercontent.com/assets/1094697/15041698/72f1428c-12f0-11e6-8bdf-6d51581d0be3.png)

**Comment by qiu8310** [comment]
暂时把 bug 关了
