### ISSUE TITLE
关于更新了npm之后snpm -v的显示内容的问题

### ISSUE THREAD

**Issue by bakabird** [qiu8310/smart-npm#67]
我更新了我的npm

    ~$ npm -v
    5.0.2

不过snpm里的npm还是旧版本的

     ~$ snpm -v
     npm:  4.4.4
     smart-npm:  3.0.1

这样有什么影响么？我现在使用snpm的时候，用的是高版本的npm还是低版本的npm呀？

**Comment by qiu8310** [comment]
snpm 用的是它自带的 npm，不是你系统里的，你可以重新安装下 snpm，就可以把 snpm 里的 npm 更新到最新版的
