### ISSUE TITLE
升级 npm后 snpm -v 显示的npm版本是老的

### ISSUE THREAD

**Issue by xiaolongyuan** [qiu8310/smart-npm#71]

**Comment by qiu8310** [comment]
snpm 使用的是自带的 npm，不是你系统的，你可以删除 snpm，再重新安装下 snpm，就会把 snpm 内部的 npm 升级到最新版了

**Comment by qiu8310** [comment]
更新了一个版本，你可以使用 snpm install-npm 来更新 snpm 内部使用的 npm

你需要升级下你本地的 smart-npm 即可 `npm up -g smart-npm`

**Comment by xiaolongyuan** [comment]
最新 npm 5.2.0 啊
