### ISSUE TITLE
Centos 7 安装失败

### ISSUE THREAD

**Issue by cnahliu** [qiu8310/smart-npm#9]
npm ERR! Error: EACCES: permission denied, open '/usr/local/etc/npmrc'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, open '/usr/local/etc/npmrc']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/usr/local/etc/npmrc' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

然，/usr/local/etc/下并没有npmrc文件。

OS:Centos 7.0
User:root
node version:v4.5.0
npm version:2.15.9

**Comment by qiu8310** [comment]
不好意思，最近比较忙，才看到。

关于你的问题，`smart-npm` 是不会用 `/usr/local/etc/npmrc` 这个文件，只会修改你个人目录下的 `~/.npmrc` 文件，所以这个错误我猜可能是 `npm` 在读取配置文件时出错了，你用 `npm` 安装其它 package 都没问题吗？

**Comment by ssfdust** [comment]
给/usr/local/etc/这个文件夹用户组加上rwx权限。这个是npm的问题，好坑。
希望有人遇见这个坑的时候可以看见。
```
chmod g+xrwx /usr/local/etc
```
